
version: "3.9"

services:
  comfyui:
    user: "1000:1000"
    build:
      context: .
      args:
        GPU_MAKE: nvidia
        EXTRA_ARGS: --disable-cuda-malloc
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    ports:
      - "8188:8188"
    volumes:
      - "./models:/app/models"
      - "./input:/app/input"
      - "./temp:/app/output/temp"
      - "./output:/app/output"
      - "./custom_nodes:/app/custom_nodes"